name: CheckInfo

on:
  workflow_dispatch:
    inputs:
      CheckInfo:
        description: "Check font info"
        required: true
        type: boolean

jobs:
  CheckInfo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download 
      run: |
        mkdir check && cd check
        curl -L -o file.tar.xz "https://github.com/5hes/MyToolBox/releases/download/v0.3.0/LLVM-ET-Arm-19.1.1-Linux-AArch64.tar.xz"
        
    - name: Extra
      run: |
        cd check
        tar -xf file.tar.xz
        rm file*
        ls

    - name: Get info
      run: |
        cd check
        ls -lah
        ls -la
        cd *
        ls -lah
        ls -la
        
        echo -e "\n\n\n\n\n11111"
        tree -L 4
        
        echo -e "\n\n\n\n\n22222"
        file bin/*

    - name: Tree
      run: tree