name: CheckInfo

on:
  workflow_dispatch:
    inputs:
      CheckInfo:
        description: "Check font info"
        required: true
        type: boolean

jobs:
  CheckInfo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Python
      run: |
        sudo apt-get update
        sudo apt-get install python3
        pip install fonttools

    - name: Download font
      run: |
        cd FontTools/MergeFont
        wget -O font1.ttf "https://github.com/5hes/Iosevka_fork/releases/download/v0.0.0.5/Iovevka-Regular-Unhinted.ttf"
        wget -O font2.ttf "https://github.com/5hes/Iosevka_fork/releases/download/v0.0.0.6/Iovevka-Regular-Unhinted.ttf"
        wget -O font3.ttf "https://github.com/JetBrains/JetBrainsMono/raw/refs/heads/master/fonts/ttf/JetBrainsMono-Medium.ttf"
        wget -O font4.ttf "https://github.com/5hes/MyToolBox/releases/download/v0.0.3/HarmonyOS_SansSC_Regular.ttf"
        
    - name: Get info
      run: |
        cd FontTools/MergeFont
        pwd
        ls -ltrah
        ls -ltra
        tree
        echo -e "\n\n\n\n\nfont1"
        python getinfo.py font1.ttf
        
        echo -e "\n\n\n\n\nfont2"
        python getinfo.py font2.ttf
        
        echo -e "\n\n\n\n\nfont3"
        python getinfo.py font3.ttf
        
        echo -e "\n\n\n\n\nfont4"
        python getinfo.py font4.ttf
        
        # echo -e "\n\n\n\n\nfont5"
        # python getinfo.py font5.ttf
        
        # echo -e "\n\n\n\n\nfont6"
        # python getinfo.py font6.ttf



        
