name: CheckInfo

on:
  workflow_dispatch:
    inputs:
      CheckInfo:
        description: "Check font info"
        required: true
        type: boolean

jobs:
  CheckInfo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download 
      run: |
        mkdir check && cd check
        curl -L -o file.zip "https://github.com/5hes/MyToolBox/releases/download/v0.3.0/Arm.Compiler.for.Embedded.FuSa.6.22.1.Toolchain.and.Qualification.Kit.AArch64.Linux.zip"
        
    - name: Extra
      run: |
        cd check
        unzip file.zip
        rm file.zip
        tar -xzf ARMCompiler6.22.1_standalone_linux-aarch64.tar.gz
        tar -xzf Arm_Compiler_for_Embedded_FuSa_Qualification_Kit_6.22.1_linux.tar.gz
        ls
        rm *tar*

    - name: Get info
      run: |
        cd check
        ls -ltrah
        ls -ltra
        cd *
        ls -ltrah
        ls -ltra

        echo -e "\n\n\n\n\n11111"
        tree -L 4
        
        echo -e "\n\n\n\n\n22222"

    - name: Tree
      run: tree