name: Custom

on:
  push:
  workflow_dispatch:
    inputs:
      task:
        description: "Custom build fonts"
        required: true
        type: boolean

permissions: write-all
jobs:
  downfont:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Push a tag
        run: |
          # NAME='v0.0.0-custom'
          # git tag "$NAME"
          # git push origin "$NAME"

      - name: Download fonts
        run: |
          mkdir work
          cd work
          wget -O font.ttf "https://github.com/5hes/Iosevka_fork/releases/download/v0.0.4-Iover/NormalGold-Medium.ttf"

      - name: Font down
        run: |
          mv FontTools/MergeFont/fontdown.py work/
          cd work
          python fontdown.py font.ttf 100 modify.ttf
          ls -ltrah && ls -ltra

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: font
          path: work/modify.ttf
      
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.0.0-custom
          name: Down NormalGold font
          files: |
            work/modify.ttf