name: Custom

on:
  push:
  workflow_dispatch:
    inputs:
      task:
        description: "Custom build fonts"
        required: true
        type: boolean

permissions: write-all
jobs:
  downfont:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Push a tag
        run: |
          # NAME='v0.0.0-custom'
          # git tag "$NAME"
          # git push origin "$NAME"

      - name: Download fonts
        run: |
          pip install fonttools
          mkdir work
          cd work
          wget -O font.ttf "https://github.com/5hes/Font/releases/download/v0.1.1/OPPO.Sans.4.0.ttf"

      - name: Font down
        run: |
          mv FontTools/MergeFont/ttf-split.py work/
          cd work
          python ttf-split.py font.ttf
          ls -ltrah && ls -ltra
          tree

#       - name: Upload
#         uses: actions/upload-artifact@v4
#         with:
#           name: font
#           path: work/**
      
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.0.0-custom
          name: Down NormalGold font
          files: |
            work/*
            work/OPPO Sans 4.0_split/*