name: Custom

on:
  push:
  workflow_dispatch:
    inputs:
      task:
        description: "Custom build fonts"
        required: true
        type: boolean

permissions: write-all
jobs:
  downfont:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Push a tag
        run: |
          # NAME='v0.0.1-custom'
          # git tag "$NAME"
          # git push origin "$NAME"

      - name: Download fonts
        run: |
          sudo apt-get install fontconfig
          pip install fonttools
          mkdir work
          cd work
          wget -O font.ttf "https://github.com/5hes/Font/releases/download/v0.1.1/OPPO.Sans.4.0.ttf"

      - name: Process
        run: |
          mv FontTools/MergeFont/var-extra.sh work/
          cd work
          chmod +x var-extra.sh
          ./var-extra.sh
          ls -ltrah && ls -ltra
          tree

      - name: Check info
        run: |
          cd work
          fc-query -b font.ttf
          echo -e "\n\n\n\n\n\n\n\n\n\n"
          
#       - name: Upload
#         uses: actions/upload-artifact@v4
#         with:
#           name: font
#           path: work/**
      
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.0.1-custom
          name: split
          files: |
            work/**