name: Custom

on:
  push:
  workflow_dispatch:
    inputs:
      task:
        description: "Custom build fonts"
        required: true
        type: boolean

jobs:
  convert_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Download fonts
        run: |
          cd work
          wget -O font.ttf "https://github.com/5hes/Iosevka_fork/releases/download/v0.0.4-Iover/NormalGold-Medium.ttf"

      - name: Font down
        run: |
          mkdir work
          mv FontTools/MyToolBox/fontdown.py work/
          cd work
          python fontdown.py font.ttf 100 modify.ttf
          ls -ltrah && ls -ltra

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: font
          path: work/modify.ttf