name: Download File

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Download File And Unzip"
        required: true
        type: boolean

jobs:
  Download:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Install Depends
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip p7zip-full tar gzip bzip2 xz-utils tree

      - name: Set Env
        shell: bash
        run: |
          chmod +x unzipper.sh env.sh
          source env.sh
      
      - name: Download
        shell: bash
        run: |
          cd Download
          wget $LINK
          ls -lah
          ./unzipper.sh
          tree
          ls -lah
                    
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET }}
          path: Download/${{ env.TARGET }}
          compression-level: 0
