name: Download File

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Download File And Unzip"
        required: true
        type: boolean

jobs:
  Download:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4
      
      - name: Download
        shell: bash
        run: |
          cd Download
          export LINK=$(cat link) && rm link
          wget $LINK
          ls -lah
          unzip $(ls)
          echo "TARGET=$(cat Download/target)" >> $GITHUB_ENV
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET }}
          path: Download/${{ env.TARGET }}
