name: Download File

on:
  push:
  workflow_dispatch:
    inputs:
      task:
        description: "Download File And Unzip"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Create a new tag
        id: create_tag
        run: |
           TAG_NAME="v0.2.6"  # 这里设置你想要的标签名
           git tag $TAG_NAME
           git push origin $TAG_NAME

      - name: Install Depends
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip p7zip-full tar gzip bzip2 xz-utils tree unrar lz4 zstd

      - name: Download
        run: |
          cd Download/
          chmod +x unzipper.sh env.sh downloader.sh
          wget -O out.tar "https://ykj-eos-dg5-01.eos-dongguan-6.cmecloud.cn/400cb751593d4ce3b156bcb0253461c4086?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27%25E5%2588%259A%25E5%2588%259A%25E6%258E%25A5%25E5%2588%25B0.tar&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250119T103037Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=9T1UKBIX6OJSR5XN2F2T%2F20250119%2Fdefault%2Fs3%2Faws4_request&t=2&u=1039816495805071512&ot=personal&oi=1039816495805071512&f=FuM_YPvjwCBqwVHujPSZC8K1tanyC8B8a&X-Amz-Signature=4ec2c1fd43bf49ec040470821b38c4d136c08f3f651b27399571595acdcd8f2f"
          # source env.sh
          # wget -O 1.7z.001 ""
          # wget -O 1.7z.002 ""
          # wget -O 1.7z.003 ""
          # wget -O 1.7z.004 "https://github.com/5hes/MyToolBox/releases/download/v0.2.0/1.7z.004"
          
#      - name: Push
#        run: |
#          git config --local user.name "github-actions"
#          git config --local user.email "github-actions@github.com"
#          git add Download/good/1
#          git commit -m "Update 1"
#          git push origin main

      - name: Unziper
        if: env.hard == 1 
        run: |
          cd Download/
          chmod +x unzipper.sh
          export EXTRA=true
          export password=awfx
          # sen1
          # jntm
          export crypt=false
          ls -ltrah
          # ./unzipper.sh
          # tar -xvf *.tar
          # echo "#!/bin/bash" > unzip
          # echo "7z x -pawfx 1.7z.001 -o crypt" > unzip
          # echo "7z x 1.7z.001" > unzip
          # chmod +x unzip
          # ./unzip
          mkdir out
          cd out
          export sb=$PWD
          cd ..

          7z x -pruoyuchen 1.7z.001 -ooutput
          tree
          cd output
          mv *001* 1.7z.001
          mv *002* 1.7z.002
          7z x -pruoyuchen 1.7z.001
          tree
          rm *7z*

          # cd output
          # 7z x -pruoyuchen *001
          # find . -name "*mp4" -exec mv {} $sb \;
          # rm -rf *
          # mv $sb/* .
          
          cd ..
          tar -zcvf out.tar output
          tree
          cd output
          ls -ltrah
      
      - name: ez unzip
        run: |
          cd Download/
          tar -xvf *.tar
          
      - name: Check
        shell: bash
        run: |
          cd Download/
          ls -ltrah
          ls -ltra
          tree
          
#      - name: Upload
#        uses: actions/upload-artifact@v4
#        with:
#          name: mp4
#          path: Download/*mp*
#          compression-level: 0


      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.2.6
          name: mp4 jd gg
          #tag_name: ${{ github.ref }}
          #name: ${{ github.ref }}
          #body: TODO New Release.
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            Download/out.tar
            Download/*mp4


#            Download/*7z*            
#            Download/out.tar
#            Download/*7z*
#            Download/HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Medium.ttf
  
            
#      - name: Upload to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: |
#            Download/084.mp4
#            Download/zip.zip
#          tag: ${{ github.ref }}
#          overwrite: true
#          file_glob: true
  
#      - name: Help
#        shell: bash
#        run: |
#          cd Download/字体合并补全工具-简体中文-1.1.0-linux-amd64
#          ./merge-otd --help
#          ./otfccbuild  --help
#          ./otfccdump  --help
                    

