name: Download File

on:
  push:
  workflow_dispatch:
    inputs:
      task:
        description: "Download File And Unzip"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Create a new tag
        id: create_tag
        run: |
          # TAG_NAME="v0.3.0"  # 这里设置你想要的标签名
          # git tag $TAG_NAME
          # git push origin $TAG_NAME

      - name: Install Depends
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip p7zip-full tar gzip bzip2 xz-utils tree unrar lz4 zstd aria2 httpie python3

      - name: Download
        run: |
          cd Download/
          chmod +x unzipper.sh env.sh downloader.sh
          curl -o ARMCompiler6.23_standalone_linux-aarch64.tar.gz "https://arm-pro-pkg-repository.s3.eu-west-2.amazonaws.com/parts/ACOMPE-BN-00030-r6p23-00rel0/ARMCompiler6.23_standalone_linux-aarch64.tar.gz?X-Amz-Security-Token=FwoGZXIvYXdzENX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDKvlWqH6fCDJQU7ijCKvAez8AdoBhwuqc0MlYyFXOvj5ylrKztfzBP62ZFN6m99sc83tGEi8NOMVJlLZa%2BKDPZnHu8UjOHA5Hvc5TB5z9GHIZbR9YXCMgFc8DoVBnxKRwdKOR%2FTbZvluVG21W8LHmnWo6xlXkDIXMeRj8tA2Fyj3cKrPsFrf94ZG%2FANj8eCnZInG90n%2B%2BtG2X0PUMyUwrD2N7ha6DBTot5z1nwNJk3%2BdcDgk9q20ipL5QjJimbEoubX2vAYyLfDMekbU4Ux9%2F6bWvd7EBvFrfMyoJKCl4m2qHH%2B8bUMBF0mz9G8mGPuoS9Xpdg%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250201T035329Z&X-Amz-SignedHeaders=host&X-Amz-Expires=599&X-Amz-Credential=ASIAUCCFPAXAVPYP3D4T%2F20250201%2Feu-west-2%2Fs3%2Faws4_request&X-Amz-Signature=b04887559f6e3dfaaf89bf8f788d9c7d04381149acce63a6570803a078978f56"
          # http --download "https://vid-s1-n10-ca-cdn.eporner.com/v5/qBCuxwt6rjuRsTRjQ9ztWQ/1737910414_64.74.163.130_1222/11993072-1080p.mp4"
          # curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3" -O "https://vid-s1-n10-ca-cdn.eporner.com/v5/qBCuxwt6rjuRsTRjQ9ztWQ/1737910414_64.74.163.130_1222/11993072-1080p.mp4"
          # wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3" -O 1080P.mp4 "https://vid-s1-n10-ca-cdn.eporner.com/v5/qBCuxwt6rjuRsTRjQ9ztWQ/1737910414_64.74.163.130_1222/11993072-1080p.mp4"
          # curl -o fast.zip ""
          # curl -o small.zip ""
          # source env.sh
          # wget -O 1.7z.001 ""
          # wget -O 1.7z.002 ""
          # wget -O 1.7z.003 ""
          # wget -O 1.7z.004 "https://github.com/5hes/MyToolBox/releases/download/v0.2.0/1.7z.004"
          
#      - name: Push
#        run: |
#          git config --local user.name "github-actions"
#          git config --local user.email "github-actions@github.com"
#          git add Download/good/1
#          git commit -m "Update 1"
#          git push origin main

      - name: Unziper
        if: env.hard == 1 
        run: |
          cd Download/
          chmod +x unzipper.sh
          export EXTRA=true
          export password=awfx
          # sen1
          # jntm
          export crypt=false
          ls -ltrah
          # ./unzipper.sh
          # tar -xvf *.tar
          # echo "#!/bin/bash" > unzip
          # echo "7z x -pawfx 1.7z.001 -o crypt" > unzip
          # echo "7z x 1.7z.001" > unzip
          # chmod +x unzip
          # ./unzip
          mkdir out
          cd out
          export sb=$PWD
          cd ..

          7z x -pruoyuchen 1.7z.001 -ooutput
          tree
          cd output
          mv *001* 1.7z.001
          mv *002* 1.7z.002
          7z x -pruoyuchen 1.7z.001
          tree
          rm *7z*

          # cd output
          # 7z x -pruoyuchen *001
          # find . -name "*mp4" -exec mv {} $sb \;
          # rm -rf *
          # mv $sb/* .
          
          cd ..
          tar -zcvf out.tar output
          tree
          cd output
          ls -ltrah
      
      - name: ez unzip
        if: env.SB == 1
        run: |
          cd Download/
          unzip fast.zip -d fast
          unzip small.zip -d small
          tar -zcf fast.tar fast
          tar -zcf small.tar small
          tar -cJf fast.tar.xz fast
          tar -cJf small.tar.xz small
          7z a fast.7z fast
          7z a small.7z small
          
      - name: Check
        shell: bash
        run: |
          cd Download/
          ls -ltrah
          ls -ltra
          tree
          
#      - name: Upload
#        uses: actions/upload-artifact@v4
#        with:
#          name: mp4
#          path: Download/*mp*
#          compression-level: 0


      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.3.0
          name: arm compiler
          #tag_name: ${{ github.ref }}
          #name: ${{ github.ref }}
          #body: TODO New Release.
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            Download/*.gz

#            Download/*.zip
#            Download/*.7z
#            Download/*.tar.xz
#            Download/*mp4
#            Download/*7z*            
#            Download/out.tar
#            Download/*7z*
#            Download/HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Medium.ttf
  
            
#      - name: Upload to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: |
#            Download/084.mp4
#            Download/zip.zip
#          tag: ${{ github.ref }}
#          overwrite: true
#          file_glob: true
  
#      - name: Help
#        shell: bash
#        run: |
#          cd Download/字体合并补全工具-简体中文-1.1.0-linux-amd64
#          ./merge-otd --help
#          ./otfccbuild  --help
#          ./otfccdump  --help
                    

