name: Download File

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Download File And Unzip"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Create a new tag
        id: create_tag
        run: |
           TAG_NAME="v0.1.4"  # 这里设置你想要的标签名
           git tag $TAG_NAME
           git push origin $TAG_NAME

      - name: Install Depends
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip p7zip-full tar gzip bzip2 xz-utils tree unrar lz4 zstd

      - name: Download
        run: |
          cd Download/
          chmod +x unzipper.sh env.sh downloader.sh
          # source env.sh
          wget -O 1.7z.001 "https://ykj-eos-dg5-01.eos-dongguan-6.cmecloud.cn/a0f0a6419bf44fe9a33f6620d574a94f086?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27jj.7z.001&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241217T133627Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=9T1UKBIX6OJSR5XN2F2T%2F20241217%2Fdefault%2Fs3%2Faws4_request&X-Amz-Signature=6bb6d6f5f80fb65795d60998cff7e3d6dc92f109fa3136d048565c7a2b5c688a"
          wget -O 1.7z.002 "https://ykj-eos-dg5-01.eos-dongguan-6.cmecloud.cn/8ce4b6341d5e48529b4a52552c32e3ce086?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27jj.7z.002&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241217T133641Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=9T1UKBIX6OJSR5XN2F2T%2F20241217%2Fdefault%2Fs3%2Faws4_request&X-Amz-Signature=91875520aeda405857d166e5ed80b8716b44c341faba1fb803fd78476fe0bab9"
          
#      - name: Push
#        run: |
#          git config --local user.name "github-actions"
#          git config --local user.email "github-actions@github.com"
#          git add Download/good/1
#          git commit -m "Update 1"
#          git push origin main

      - name: Unziper
        run: |
          cd Download/
          chmod +x unzipper.sh
          export EXTRA=true
          export password=sen1
          export crypt=true
          ls -ltrah
          ./unzipper.sh
          tree
          ls -ltrah

      - name: Check
        shell: bash
        run: |
          cd Download/
          ls -ltrah
          ls -ltra
          tree
          
#      - name: Upload
#        uses: actions/upload-artifact@v4
#        with:
#          name: mp4
#          path: Download/*mp*
#          compression-level: 0


      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.1.4 # 使用创建的标签
          name: mp4-xh
          #tag_name: ${{ github.ref }}
          #name: ${{ github.ref }}
          #body: TODO New Release.
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            Download/*mp*



#            Download/HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Medium.ttf
  
            
#      - name: Upload to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: |
#            Download/084.mp4
#            Download/zip.zip
#          tag: ${{ github.ref }}
#          overwrite: true
#          file_glob: true
  
#      - name: Help
#        shell: bash
#        run: |
#          cd Download/字体合并补全工具-简体中文-1.1.0-linux-amd64
#          ./merge-otd --help
#          ./otfccbuild  --help
#          ./otfccdump  --help
                    

