name: Download File

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Download File And Unzip"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Create a new tag
        id: create_tag
        run: |
           # TAG_NAME="v0.1.6"  # 这里设置你想要的标签名
           # git tag $TAG_NAME
           # git push origin $TAG_NAME

      - name: Install Depends
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip p7zip-full tar gzip bzip2 xz-utils tree unrar lz4 zstd

      - name: Download
        run: |
          cd Download/
          chmod +x unzipper.sh env.sh downloader.sh
          # source env.sh
          wget -O zip.zip "https://productionresultssa18.blob.core.windows.net/actions-results/77296c63-2f6d-4dca-9c28-8e89da64c990/workflow-job-run-5015ee18-cc8d-5890-6f18-7451317b8c86/artifacts/65e83a561328b64c7fd3d380ab32607ceac84ce62fd8a8da2a0235b475de6ed4.zip?rscd=attachment%3B+filename%3D%22termux-app_v0.118.0%2B5fec235-apt-android-7-github-release_arm64-v8a.zip%22&se=2024-12-23T13%3A39%3A40Z&sig=uAbmNF56pEx47I1EOa7r4D2SzeUBkdkD%2BkDOOXrHSH4%3D&ske=2024-12-23T23%3A01%3A16Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-12-23T11%3A01%3A16Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-11-04&sp=r&spr=https&sr=b&st=2024-12-23T13%3A29%3A35Z&sv=2024-11-04"
          # wget -O 1.7z.001 ""
          # wget -O 1.7z.002 ""
          
#      - name: Push
#        run: |
#          git config --local user.name "github-actions"
#          git config --local user.email "github-actions@github.com"
#          git add Download/good/1
#          git commit -m "Update 1"
#          git push origin main

      - name: Unziper
        run: |
          cd Download/
          chmod +x unzipper.sh
          export EXTRA=true
          export password=sen1
          export crypt=false
          ls -ltrah
          ./unzipper.sh
          tree
          ls -ltrah

      - name: Check
        shell: bash
        run: |
          cd Download/
          ls -ltrah
          ls -ltra
          tree
          
#      - name: Upload
#        uses: actions/upload-artifact@v4
#        with:
#          name: mp4
#          path: Download/*mp*
#          compression-level: 0


      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.1.6 # 使用创建的标签
          name: termux(Buildtype Release)
          #tag_name: ${{ github.ref }}
          #name: ${{ github.ref }}
          #body: TODO New Release.
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            Download/*.apk



#            Download/HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Medium.ttf
  
            
#      - name: Upload to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: |
#            Download/084.mp4
#            Download/zip.zip
#          tag: ${{ github.ref }}
#          overwrite: true
#          file_glob: true
  
#      - name: Help
#        shell: bash
#        run: |
#          cd Download/字体合并补全工具-简体中文-1.1.0-linux-amd64
#          ./merge-otd --help
#          ./otfccbuild  --help
#          ./otfccdump  --help
                    

