name: Download File

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Download File And Unzip"
        required: true
        type: boolean
        
jobs:
  Download:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Install Depends
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip p7zip-full tar gzip bzip2 xz-utils tree unrar lz4 zstd


      - name: Set Env And Download
        shell: bash
        run: |
          cd Download
          chmod +x unzipper.sh env.sh
          source env.sh
          wget $LINK
          ls -ltrah
          ./unzipper.sh
          tree
          ls -ltrah
          cd 字体合并补全工具-简体中文-1.1.0-linux-amd64
          ls -ltrah
          ls -ltra
          rm cjk.ttf

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET }}
          path: Download/${{ env.TARGET }}
          compression-level: 0

      - name: Help
        shell: bash
        run: |
          cd Download/字体合并补全工具-简体中文-1.1.0-linux-amd64
          ./merge-otd --help
          ./otfccbuild  --help
          ./otfccdump  --help
                    

