name: Download File

on:
  push:
  workflow_dispatch:
    inputs:
      task:
        description: "Download File And Unzip"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Create a new tag
        id: create_tag
        run: |
           TAG_NAME="v0.2.9"  # 这里设置你想要的标签名
           git tag $TAG_NAME
           git push origin $TAG_NAME

      - name: Install Depends
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip p7zip-full tar gzip bzip2 xz-utils tree unrar lz4 zstd

      - name: Download
        run: |
          cd Download/
          chmod +x unzipper.sh env.sh downloader.sh
          curl -o fast.zip "https://productionresultssa1.blob.core.windows.net/actions-results/815f033c-c3d5-4e87-8ac5-3914aa7bc7b4/workflow-job-run-b8f2bbbf-950a-55df-8093-e7d8c87fa511/artifacts/6c582b62e0e5aa05647388bd045f2e3e5e7f51f479d00d9df592634c8088a22b.zip?rscd=attachment%3B+filename%3D%22Fast.zip%22&se=2025-01-20T11%3A42%3A40Z&sig=dsh8mV72BPFoQuyWyTKA%2BFLt9AkplisErBvUYOHJOdw%3D&ske=2025-01-20T22%3A47%3A39Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-01-20T10%3A47%3A39Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-11-04&sp=r&spr=https&sr=b&st=2025-01-20T11%3A32%3A35Z&sv=2024-11-04"
          curl -o small.zip "https://productionresultssa1.blob.core.windows.net/actions-results/815f033c-c3d5-4e87-8ac5-3914aa7bc7b4/workflow-job-run-795fb78b-e756-56a2-288a-77f8b61e4c53/artifacts/5263293fc202649bdc8135573ac9cd3b0bcea4355e0d8f0a59f1ddeea8eefc15.zip?rscd=attachment%3B+filename%3D%22Small.zip%22&se=2025-01-20T11%3A42%3A13Z&sig=TM2XGRHaIODvwnm70x%2FjnQruF1Uf728Sfu37xirPdT8%3D&ske=2025-01-20T22%3A53%3A39Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-01-20T10%3A53%3A39Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-11-04&sp=r&spr=https&sr=b&st=2025-01-20T11%3A32%3A08Z&sv=2024-11-04"
          # source env.sh
          # wget -O 1.7z.001 ""
          # wget -O 1.7z.002 ""
          # wget -O 1.7z.003 ""
          # wget -O 1.7z.004 "https://github.com/5hes/MyToolBox/releases/download/v0.2.0/1.7z.004"
          
#      - name: Push
#        run: |
#          git config --local user.name "github-actions"
#          git config --local user.email "github-actions@github.com"
#          git add Download/good/1
#          git commit -m "Update 1"
#          git push origin main

      - name: Unziper
        if: env.hard == 1 
        run: |
          cd Download/
          chmod +x unzipper.sh
          export EXTRA=true
          export password=awfx
          # sen1
          # jntm
          export crypt=false
          ls -ltrah
          # ./unzipper.sh
          # tar -xvf *.tar
          # echo "#!/bin/bash" > unzip
          # echo "7z x -pawfx 1.7z.001 -o crypt" > unzip
          # echo "7z x 1.7z.001" > unzip
          # chmod +x unzip
          # ./unzip
          mkdir out
          cd out
          export sb=$PWD
          cd ..

          7z x -pruoyuchen 1.7z.001 -ooutput
          tree
          cd output
          mv *001* 1.7z.001
          mv *002* 1.7z.002
          7z x -pruoyuchen 1.7z.001
          tree
          rm *7z*

          # cd output
          # 7z x -pruoyuchen *001
          # find . -name "*mp4" -exec mv {} $sb \;
          # rm -rf *
          # mv $sb/* .
          
          cd ..
          tar -zcvf out.tar output
          tree
          cd output
          ls -ltrah
      
      - name: ez unzip
        run: |
          cd Download/
          unzip fast.zip -d fast
          unzip small.zip -d small
          tar -zcf fast.tar fast
          tar -zcf small.tar small
          tar -cJf fast.tar.xz fast
          tar -cJf small.tar.xz small
          7z a fast.7z fast
          7z a small.7z small
          
      - name: Check
        shell: bash
        run: |
          cd Download/
          ls -ltrah
          ls -ltra
          tree
          
#      - name: Upload
#        uses: actions/upload-artifact@v4
#        with:
#          name: mp4
#          path: Download/*mp*
#          compression-level: 0


      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.2.9
          name: zig 14-dev d5db02728ce3ff3ba74a3e3f9050c3ea9ed34752
          #tag_name: ${{ github.ref }}
          #name: ${{ github.ref }}
          #body: TODO New Release.
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            Download/*.tar
            Download/*.zip
            Download/*.7z
            Download/*.tar.xz

#            Download/*mp4
#            Download/*7z*            
#            Download/out.tar
#            Download/*7z*
#            Download/HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Medium.ttf
  
            
#      - name: Upload to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: |
#            Download/084.mp4
#            Download/zip.zip
#          tag: ${{ github.ref }}
#          overwrite: true
#          file_glob: true
  
#      - name: Help
#        shell: bash
#        run: |
#          cd Download/字体合并补全工具-简体中文-1.1.0-linux-amd64
#          ./merge-otd --help
#          ./otfccbuild  --help
#          ./otfccdump  --help
                    

