name: Download File

on:
  push:
  workflow_dispatch:
    inputs:
      task:
        description: "Download File And Unzip"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Create a new tag
        id: create_tag
        run: |
           # TAG_NAME="v0.2.0"  # 这里设置你想要的标签名
           # git tag $TAG_NAME
           # git push origin $TAG_NAME

      - name: Install Depends
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip p7zip-full tar gzip bzip2 xz-utils tree unrar lz4 zstd

      - name: Download
        run: |
          cd Download/
          chmod +x unzipper.sh env.sh downloader.sh
          # source env.sh
          wget -O 1.7z.001 "https://github.com/5hes/MyToolBox/releases/download/v0.2.0/1.7z.001"
          wget -O 1.7z.002 "https://github.com/5hes/MyToolBox/releases/download/v0.2.0/1.7z.002"
          wget -O 1.7z.003 "https://github.com/5hes/MyToolBox/releases/download/v0.2.0/1.7z.003"
          wget -O 1.7z.004 "https://github.com/5hes/MyToolBox/releases/download/v0.2.0/1.7z.004"
          
#      - name: Push
#        run: |
#          git config --local user.name "github-actions"
#          git config --local user.email "github-actions@github.com"
#          git add Download/good/1
#          git commit -m "Update 1"
#          git push origin main

      - name: Unziper
        run: |
          cd Download/
          chmod +x unzipper.sh
          export EXTRA=true
          export password=awfx
          # sen1
          export crypt=false
          ls -ltrah
          # ./unzipper.sh
          mkdir crypt
          # echo "#!/bin/bash" > unzip
          # echo "7z x -pawfx 1.7z.001 -o crypt" > unzip
          # echo "7z x 1.7z.001" > unzip
          # chmod +x unzip
          # ./unzip
          7z x -pjntm 1.7z.001 -o output
          tree
          ls -ltrah

      - name: Check
        shell: bash
        run: |
          cd Download/
          ls -ltrah
          ls -ltra
          tree
          
#      - name: Upload
#        uses: actions/upload-artifact@v4
#        with:
#          name: mp4
#          path: Download/*mp*
#          compression-level: 0


      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.2.0
          name: mp4 dy tyyuki
          #tag_name: ${{ github.ref }}
          #name: ${{ github.ref }}
          #body: TODO New Release.
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            Download/output/**
            


#            Download/*7z*
#            Download/HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Medium.ttf
  
            
#      - name: Upload to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: |
#            Download/084.mp4
#            Download/zip.zip
#          tag: ${{ github.ref }}
#          overwrite: true
#          file_glob: true
  
#      - name: Help
#        shell: bash
#        run: |
#          cd Download/字体合并补全工具-简体中文-1.1.0-linux-amd64
#          ./merge-otd --help
#          ./otfccbuild  --help
#          ./otfccdump  --help
                    

