name: Download File

on:
  push:
  workflow_dispatch:
    inputs:
      task:
        description: "Download File And Unzip"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Create a new tag
        id: create_tag
        run: |
           # TAG_NAME="v0.1.7"  # 这里设置你想要的标签名
           # git tag $TAG_NAME
           # git push origin $TAG_NAME

      - name: Install Depends
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip p7zip-full tar gzip bzip2 xz-utils tree unrar lz4 zstd

      - name: Download
        run: |
          cd Download/
          chmod +x unzipper.sh env.sh downloader.sh
          # source env.sh
          wget -O 1.7z.001 "https://ykj-eos-wx2-01.eos-wuxi-3.cmecloud.cn/d9fd85f06dc745b198905465d2687263086?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27%25E5%25A6%25B9%25E5%25A6%25B9%25E8%25A2%25AB%25E5%2593%25A5%25E5%2593%25A5%25E7%258B%2582%25E5%25B9%25B2.zip.001&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250116T000424Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=Y60FITYLOX7N6UJWBOEE%2F20250116%2Fdefault%2Fs3%2Faws4_request&t=2&u=1039816495805071512&ot=personal&oi=1039816495805071512&f=FrfwCrZUnCofaf_VKrvZCjrhesO_vJx2H&X-Amz-Signature=cc38f5042fee0019d142074c977a18d22bc217fa1181e741d72ab86aa2d8b2cf"
          wget -O 1.7z.002 "https://ykj-eos-wx2-01.eos-wuxi-3.cmecloud.cn/7662ecdd60a1462abcba52cc7fae4716086?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27%25E5%25A6%25B9%25E5%25A6%25B9%25E8%25A2%25AB%25E5%2593%25A5%25E5%2593%25A5%25E7%258B%2582%25E5%25B9%25B2.zip.002&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250116T000416Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=Y60FITYLOX7N6UJWBOEE%2F20250116%2Fdefault%2Fs3%2Faws4_request&t=2&u=1039816495805071512&ot=personal&oi=1039816495805071512&f=FgnWe7RLdf2BN7Fml5WNKo5fXLK9o3Whg&X-Amz-Signature=a575afc8e3eb57cbe23ff2943dbcf75c19e9055a3b8e4728c7b9c408be041c38"
          
#      - name: Push
#        run: |
#          git config --local user.name "github-actions"
#          git config --local user.email "github-actions@github.com"
#          git add Download/good/1
#          git commit -m "Update 1"
#          git push origin main

      - name: Unziper
        run: |
          cd Download/
          chmod +x unzipper.sh
          export EXTRA=true
          export password=awfx
          # sen1
          export crypt=false
          ls -ltrah
          # ./unzipper.sh
          mkdir crypt
          echo "#!/bin/bash" > unzip
          # echo "7z x -pawfx 1.7z.001 -o crypt" > unzip
          echo "7z x 1.7z.001" > unzip
          chmod +x unzip
          ./unzip
          tree
          ls -ltrah

      - name: Check
        shell: bash
        run: |
          cd Download/
          ls -ltrah
          ls -ltra
          tree
          
#      - name: Upload
#        uses: actions/upload-artifact@v4
#        with:
#          name: mp4
#          path: Download/*mp*
#          compression-level: 0


      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.1.7
          name: mp4 grt
          #tag_name: ${{ github.ref }}
          #name: ${{ github.ref }}
          #body: TODO New Release.
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            Download/*.mp4
            Download/crypt/*.mp4



#            Download/HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Medium.ttf
  
            
#      - name: Upload to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: |
#            Download/084.mp4
#            Download/zip.zip
#          tag: ${{ github.ref }}
#          overwrite: true
#          file_glob: true
  
#      - name: Help
#        shell: bash
#        run: |
#          cd Download/字体合并补全工具-简体中文-1.1.0-linux-amd64
#          ./merge-otd --help
#          ./otfccbuild  --help
#          ./otfccdump  --help
                    

