name: Download File

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Download File And Unzip"
        required: true
        type: boolean

permissions:
  contents: write  # 允许写入内容
  issues: write    # 允许写入问题
  pull-requests: write  # 允许写入拉取请求
        
jobs:
  Download:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Create a new tag
        id: create_tag
        run: |
           TAG_NAME="v0.0.5"  # 这里设置你想要的标签名
           git tag $TAG_NAME
           git push origin $TAG_NAME

      - name: Install Depends
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip p7zip-full tar gzip bzip2 xz-utils tree unrar lz4 zstd

      - name: Set Env And Download
        shell: bash
        run: |
          cd Download
          chmod +x unzipper.sh env.sh
          source env.sh
          export EXTRA=true
          export password=sy66
          export crypt=false
          wget -q -O 1.7z.001 "https://dl-pc-zb-cf.pds.quark.cn/vmf1VyR9/3295366390/66fd585d1f82f7912d8c4f68a7cb50254c20cdd3/66fd585d7faad73002e1413cbb15f60f60df70d0?Expires=1733507624&OSSAccessKeyId=LTAI5tJJpWQEfrcKHnd1LqsZ&Signature=IjmaidNExW1YxNcGccNmZZvWKd8%3D&x-oss-traffic-limit=503316480&response-content-disposition=attachment%3B%20filename%3D%25E6%2589%25BE930%2520%25287%2529.7z.001%3Bfilename%2A%3Dutf-8%27%27%25E6%2589%25BE930%2520%25287%2529.7z.001&callback-var=eyJ4OmF1IjoiLSIsIng6dWQiOiIxNi0wLTUtMi02LU4tNC1OLTEtMTYtMC1OIiwieDpzcCI6IjEwMCIsIng6dG9rZW4iOiI0LWZkYTA2ZjY3NGRkZWExNzdkN2JiZWYxNTBhOTJmNGNlLTgtMS01MDAtNjAxY2E2ZmEzNDMwNDUyZWJhNzAwYzU5OTdmZjlhODMtMC0wLTAtMC00M2MwZTUyZWE4NjU4ZTU2OTVhZmY3ZDBkNTQxZjhmYiIsIng6dHRsIjoiMjE2MDAifQ%3D%3D&callback=eyJjYWxsYmFja0JvZHlUeXBlIjoiYXBwbGljYXRpb24vanNvbiIsImNhbGxiYWNrU3RhZ2UiOiJiZWZvcmUtZXhlY3V0ZSIsImNhbGxiYWNrRmFpbHVyZUFjdGlvbiI6Imlnbm9yZSIsImNhbGxiYWNrVXJsIjoiaHR0cHM6Ly9hdXRoLWNkbi51Yy5jbi9vdXRlci9vc3MvY2hlY2twbGF5IiwiY2FsbGJhY2tCb2R5Ijoie1wiaG9zdFwiOiR7aHR0cEhlYWRlci5ob3N0fSxcInNpemVcIjoke3NpemV9LFwicmFuZ2VcIjoke2h0dHBIZWFkZXIucmFuZ2V9LFwicmVmZXJlclwiOiR7aHR0cEhlYWRlci5yZWZlcmVyfSxcImNvb2tpZVwiOiR7aHR0cEhlYWRlci5jb29raWV9LFwibWV0aG9kXCI6JHtodHRwSGVhZGVyLm1ldGhvZH0sXCJpcFwiOiR7Y2xpZW50SXB9LFwicG9ydFwiOiR7Y2xpZW50UG9ydH0sXCJvYmplY3RcIjoke29iamVjdH0sXCJzcFwiOiR7eDpzcH0sXCJ1ZFwiOiR7eDp1ZH0sXCJ0b2tlblwiOiR7eDp0b2tlbn0sXCJhdVwiOiR7eDphdX0sXCJ0dGxcIjoke3g6dHRsfSxcImR0X3NwXCI6JHt4OmR0X3NwfSxcImhzcFwiOiR7eDpoc3B9LFwiY2xpZW50X3Rva2VuXCI6JHtxdWVyeVN0cmluZy5jbGllbnRfdG9rZW59fSJ9&ud=16-0-5-2-6-N-4-N-1-16-0-N"&
          wget -q -O 1.7z.002 "https://dl-pc-zb-cf.pds.quark.cn/093pYFaD/2272137750/66fd4abcf444138cb1cd4749a174e39a57f06888/66fd4abcffcdfccde7654319b703e344bd82f39b?Expires=1733507624&OSSAccessKeyId=LTAI5tJJpWQEfrcKHnd1LqsZ&Signature=yfh4oi2NVigEPWkMJVTP6xY7xp4%3D&x-oss-traffic-limit=503316480&response-content-disposition=attachment%3B%20filename%3D%25E6%2589%25BE930%2520%25287%2529.7z.002%3Bfilename%2A%3Dutf-8%27%27%25E6%2589%25BE930%2520%25287%2529.7z.002&callback-var=eyJ4OmF1IjoiLSIsIng6dWQiOiIxNi0wLTYtMi02LU4tNC1OLTEtMTYtMC1OIiwieDpzcCI6IjEwMCIsIng6dG9rZW4iOiI0LWZkYTA2ZjY3NGRkZWExNzdkN2JiZWYxNTBhOTJmNGNlLTgtMS01MDAtZDFiOWVmNzFkZjhlNDkyOTg2ZWVmZjZmNTZhMDdiNmEtMC0wLTAtMC0wMmZmNDE2YzQwOTZjYzA5OWVhNzY2OTgyYWM0YTYwZCIsIng6dHRsIjoiMjE2MDAifQ%3D%3D&callback=eyJjYWxsYmFja0JvZHlUeXBlIjoiYXBwbGljYXRpb24vanNvbiIsImNhbGxiYWNrU3RhZ2UiOiJiZWZvcmUtZXhlY3V0ZSIsImNhbGxiYWNrRmFpbHVyZUFjdGlvbiI6Imlnbm9yZSIsImNhbGxiYWNrVXJsIjoiaHR0cHM6Ly9hdXRoLWNkbi51Yy5jbi9vdXRlci9vc3MvY2hlY2twbGF5IiwiY2FsbGJhY2tCb2R5Ijoie1wiaG9zdFwiOiR7aHR0cEhlYWRlci5ob3N0fSxcInNpemVcIjoke3NpemV9LFwicmFuZ2VcIjoke2h0dHBIZWFkZXIucmFuZ2V9LFwicmVmZXJlclwiOiR7aHR0cEhlYWRlci5yZWZlcmVyfSxcImNvb2tpZVwiOiR7aHR0cEhlYWRlci5jb29raWV9LFwibWV0aG9kXCI6JHtodHRwSGVhZGVyLm1ldGhvZH0sXCJpcFwiOiR7Y2xpZW50SXB9LFwicG9ydFwiOiR7Y2xpZW50UG9ydH0sXCJvYmplY3RcIjoke29iamVjdH0sXCJzcFwiOiR7eDpzcH0sXCJ1ZFwiOiR7eDp1ZH0sXCJ0b2tlblwiOiR7eDp0b2tlbn0sXCJhdVwiOiR7eDphdX0sXCJ0dGxcIjoke3g6dHRsfSxcImR0X3NwXCI6JHt4OmR0X3NwfSxcImhzcFwiOiR7eDpoc3B9LFwiY2xpZW50X3Rva2VuXCI6JHtxdWVyeVN0cmluZy5jbGllbnRfdG9rZW59fSJ9&ud=16-0-6-2-6-N-4-N-1-16-0-N"&
          wget -q -O 1.7z.003 "https://dl-pc-zb.pds.quark.cn/USuD641k/3295366390/66fd585d286c62ec2b4d428aa943cbb522651253/66fd585d519fe80e2b544cd1b352089383f0ad1d?Expires=1733507624&OSSAccessKeyId=LTAI5tJJpWQEfrcKHnd1LqsZ&Signature=9n3UPqs%2F76ite01GMpTRvMO6d4I%3D&x-oss-traffic-limit=503316480&response-content-disposition=attachment%3B%20filename%3D%25E6%2589%25BE930%2520%25287%2529.7z.003%3Bfilename%2A%3Dutf-8%27%27%25E6%2589%25BE930%2520%25287%2529.7z.003&callback-var=eyJ4OmF1IjoiLSIsIng6dWQiOiIxNi0wLTYtMi02LU4tNC1OLTEtMTYtMC1OIiwieDpzcCI6IjEwMCIsIng6dG9rZW4iOiI0LWZkYTA2ZjY3NGRkZWExNzdkN2JiZWYxNTBhOTJmNGNlLTgtMS01MDAtNmQ1NzA4ZDFlZDQyNGEzNWFlYzBlNDY2YjkyOWQ4MDctMC0wLTAtMC1lMmJhNGVmODJjMmZlYzcwMThlZWRiODJiNDdiMjdjMSIsIng6dHRsIjoiMjE2MDAifQ%3D%3D&callback=eyJjYWxsYmFja0JvZHlUeXBlIjoiYXBwbGljYXRpb24vanNvbiIsImNhbGxiYWNrU3RhZ2UiOiJiZWZvcmUtZXhlY3V0ZSIsImNhbGxiYWNrRmFpbHVyZUFjdGlvbiI6Imlnbm9yZSIsImNhbGxiYWNrVXJsIjoiaHR0cHM6Ly9hdXRoLWNkbi51Yy5jbi9vdXRlci9vc3MvY2hlY2twbGF5IiwiY2FsbGJhY2tCb2R5Ijoie1wiaG9zdFwiOiR7aHR0cEhlYWRlci5ob3N0fSxcInNpemVcIjoke3NpemV9LFwicmFuZ2VcIjoke2h0dHBIZWFkZXIucmFuZ2V9LFwicmVmZXJlclwiOiR7aHR0cEhlYWRlci5yZWZlcmVyfSxcImNvb2tpZVwiOiR7aHR0cEhlYWRlci5jb29raWV9LFwibWV0aG9kXCI6JHtodHRwSGVhZGVyLm1ldGhvZH0sXCJpcFwiOiR7Y2xpZW50SXB9LFwicG9ydFwiOiR7Y2xpZW50UG9ydH0sXCJvYmplY3RcIjoke29iamVjdH0sXCJzcFwiOiR7eDpzcH0sXCJ1ZFwiOiR7eDp1ZH0sXCJ0b2tlblwiOiR7eDp0b2tlbn0sXCJhdVwiOiR7eDphdX0sXCJ0dGxcIjoke3g6dHRsfSxcImR0X3NwXCI6JHt4OmR0X3NwfSxcImhzcFwiOiR7eDpoc3B9LFwiY2xpZW50X3Rva2VuXCI6JHtxdWVyeVN0cmluZy5jbGllbnRfdG9rZW59fSJ9&ud=16-0-6-2-6-N-4-N-1-16-0-N"&
          wget -q -O 1.7z.004 "https://dl-pc-zb.pds.quark.cn/SdF9kYOw/2272137750/66fd4abc5fe46dcde4684df296393419766fb108/66fd4abc87867793f5fa44a9ba248b7ec5fff476?Expires=1733507624&OSSAccessKeyId=LTAI5tJJpWQEfrcKHnd1LqsZ&Signature=83MPnGtKNMZJ87kvAe5Fi%2FLLtRk%3D&x-oss-traffic-limit=503316480&response-content-disposition=attachment%3B%20filename%3D%25E6%2589%25BE930%2520%25287%2529.7z.004%3Bfilename%2A%3Dutf-8%27%27%25E6%2589%25BE930%2520%25287%2529.7z.004&callback-var=eyJ4OmF1IjoiLSIsIng6dWQiOiIxNi0wLTYtMi02LU4tNC1OLTEtMTYtMC1OIiwieDpzcCI6IjEwMCIsIng6dG9rZW4iOiI0LWZkYTA2ZjY3NGRkZWExNzdkN2JiZWYxNTBhOTJmNGNlLTgtMS01MDAtZmZiNTg2YWU2ZWY4NGVjZTliOTE2ZWYyYTQwOGNhOTctMC0wLTAtMC05NWU2Mzc5ZGEzMzM2OTJhMmE2M2NkMDhjN2IyMmMxNyIsIng6dHRsIjoiMjE2MDAifQ%3D%3D&callback=eyJjYWxsYmFja0JvZHlUeXBlIjoiYXBwbGljYXRpb24vanNvbiIsImNhbGxiYWNrU3RhZ2UiOiJiZWZvcmUtZXhlY3V0ZSIsImNhbGxiYWNrRmFpbHVyZUFjdGlvbiI6Imlnbm9yZSIsImNhbGxiYWNrVXJsIjoiaHR0cHM6Ly9hdXRoLWNkbi51Yy5jbi9vdXRlci9vc3MvY2hlY2twbGF5IiwiY2FsbGJhY2tCb2R5Ijoie1wiaG9zdFwiOiR7aHR0cEhlYWRlci5ob3N0fSxcInNpemVcIjoke3NpemV9LFwicmFuZ2VcIjoke2h0dHBIZWFkZXIucmFuZ2V9LFwicmVmZXJlclwiOiR7aHR0cEhlYWRlci5yZWZlcmVyfSxcImNvb2tpZVwiOiR7aHR0cEhlYWRlci5jb29raWV9LFwibWV0aG9kXCI6JHtodHRwSGVhZGVyLm1ldGhvZH0sXCJpcFwiOiR7Y2xpZW50SXB9LFwicG9ydFwiOiR7Y2xpZW50UG9ydH0sXCJvYmplY3RcIjoke29iamVjdH0sXCJzcFwiOiR7eDpzcH0sXCJ1ZFwiOiR7eDp1ZH0sXCJ0b2tlblwiOiR7eDp0b2tlbn0sXCJhdVwiOiR7eDphdX0sXCJ0dGxcIjoke3g6dHRsfSxcImR0X3NwXCI6JHt4OmR0X3NwfSxcImhzcFwiOiR7eDpoc3B9LFwiY2xpZW50X3Rva2VuXCI6JHtxdWVyeVN0cmluZy5jbGllbnRfdG9rZW59fSJ9&ud=16-0-6-2-6-N-4-N-1-16-0-N"&
          wget -q -O 1.7z.005 "https://dl-pc-zb.pds.quark.cn/alzlYB9f/3295366390/66fd58c0ece64be57a3347119e4fff1cc1cdc241/66fd58c098e5f23dc75a4cc58886217750ccccd9?Expires=1733507624&OSSAccessKeyId=LTAI5tJJpWQEfrcKHnd1LqsZ&Signature=wRG%2BQ9mOISDdon%2BCg%2Bm7cVB0jZI%3D&x-oss-traffic-limit=503316480&response-content-disposition=attachment%3B%20filename%3D%25E6%2589%25BE930%2520%25287%2529.7z.005%3Bfilename%2A%3Dutf-8%27%27%25E6%2589%25BE930%2520%25287%2529.7z.005&callback-var=eyJ4OmF1IjoiLSIsIng6aHNwIjoicXVhcmtfbm9uX3BlcnNvbmFsX3NtYWxsX2ZpbGUiLCJ4OnVkIjoiMTYtMC02LTItNi1OLTQtTi0xLTE2LTAtTiIsIng6c3AiOiIxMDAiLCJ4OnRva2VuIjoiNC1mZGEwNmY2NzRkZGVhMTc3ZDdiYmVmMTUwYTkyZjRjZS04LTEtMjAwLTk5NWU4NDg1NTJlMDRkN2ViMDljNTQ3ZTQ0YzRlODQ2LTAtMC0wLTAtOWVkYmM1MTY4ZjUwN2QzNWQzNmJkNzA1YTQzOWEzNGYiLCJ4OnR0bCI6IjIxNjAwIn0%3D&callback=eyJjYWxsYmFja0JvZHlUeXBlIjoiYXBwbGljYXRpb24vanNvbiIsImNhbGxiYWNrU3RhZ2UiOiJiZWZvcmUtZXhlY3V0ZSIsImNhbGxiYWNrRmFpbHVyZUFjdGlvbiI6Imlnbm9yZSIsImNhbGxiYWNrVXJsIjoiaHR0cHM6Ly9hdXRoLWNkbi51Yy5jbi9vdXRlci9vc3MvY2hlY2twbGF5IiwiY2FsbGJhY2tCb2R5Ijoie1wiaG9zdFwiOiR7aHR0cEhlYWRlci5ob3N0fSxcInNpemVcIjoke3NpemV9LFwicmFuZ2VcIjoke2h0dHBIZWFkZXIucmFuZ2V9LFwicmVmZXJlclwiOiR7aHR0cEhlYWRlci5yZWZlcmVyfSxcImNvb2tpZVwiOiR7aHR0cEhlYWRlci5jb29raWV9LFwibWV0aG9kXCI6JHtodHRwSGVhZGVyLm1ldGhvZH0sXCJpcFwiOiR7Y2xpZW50SXB9LFwicG9ydFwiOiR7Y2xpZW50UG9ydH0sXCJvYmplY3RcIjoke29iamVjdH0sXCJzcFwiOiR7eDpzcH0sXCJ1ZFwiOiR7eDp1ZH0sXCJ0b2tlblwiOiR7eDp0b2tlbn0sXCJhdVwiOiR7eDphdX0sXCJ0dGxcIjoke3g6dHRsfSxcImR0X3NwXCI6JHt4OmR0X3NwfSxcImhzcFwiOiR7eDpoc3B9LFwiY2xpZW50X3Rva2VuXCI6JHtxdWVyeVN0cmluZy5jbGllbnRfdG9rZW59fSJ9&ud=16-0-6-2-6-N-4-N-1-16-0-N"&
          wait
          ls -ltrah
          ./unzipper.sh
          tree
          ls -ltrah

      - name: Check
        shell: bash
        run: |
          cd Download
          ls -ltrah
          ls -ltra
          tree
          
#      - name: Upload
#        uses: actions/upload-artifact@v4
#        with:
#          name: mp4
#          path: Download/*mp*
#          compression-level: 0


      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.0.5  # 使用创建的标签
          name: mp4
          #tag_name: ${{ github.ref }}
          #name: ${{ github.ref }}
          #body: TODO New Release.
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            Download/**



#            Download/HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Medium.ttf
  
            
#      - name: Upload to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: |
#            Download/084.mp4
#            Download/zip.zip
#          tag: ${{ github.ref }}
#          overwrite: true
#          file_glob: true
  
#      - name: Help
#        shell: bash
#        run: |
#          cd Download/字体合并补全工具-简体中文-1.1.0-linux-amd64
#          ./merge-otd --help
#          ./otfccbuild  --help
#          ./otfccdump  --help
                    

