name: Download File

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Download File And Unzip"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Create a new tag
        id: create_tag
        run: |
           TAG_NAME="v0.0.7"  # 这里设置你想要的标签名
           git tag $TAG_NAME
           git push origin $TAG_NAME

      - name: Install Depends
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip p7zip-full tar gzip bzip2 xz-utils tree unrar lz4 zstd

      - name: Download
        run: |
          cd Download/
          chmod +x unzipper.sh env.sh downloader.sh
          # source env.sh
          wget -O 1.7z.001 "https://ykj-eos-wx2-01.eos-wuxi-3.cmecloud.cn/8f0b28b05cba4e23b10c182d3539c996086?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27%25E8%2590%259D%25E8%258E%2589%25EF%25BC%258C%25E6%25B8%2585%25E7%25BA%25AF%25E8%2590%259D%25E8%258E%2589%25E9%25A9%25AC%25E5%25B0%25BE.7z.001&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241207T091614Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=Y60FITYLOX7N6UJWBOEE%2F20241207%2Fdefault%2Fs3%2Faws4_request&X-Amz-Signature=c15b8c5e9b21297840f1e9bbcd4f6442238ddec6edf643e891df8aa7d604201f"
          wget -O 1.7z.002 "https://ykj-eos-wx2-01.eos-wuxi-3.cmecloud.cn/7508388f41a446eea5e2502239587118086?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27%25E8%2590%259D%25E8%258E%2589%25EF%25BC%258C%25E6%25B8%2585%25E7%25BA%25AF%25E8%2590%259D%25E8%258E%2589%25E9%25A9%25AC%25E5%25B0%25BE.7z.002&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241207T091624Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=Y60FITYLOX7N6UJWBOEE%2F20241207%2Fdefault%2Fs3%2Faws4_request&X-Amz-Signature=6b81c63a201c97e1e84da2ac096e7e5aad56c510635ccf588f63f3f44424f8e4"
          wget -O 1.7z.003 "https://ykj-eos-wx2-01.eos-wuxi-3.cmecloud.cn/a976aedf4b83425da106461050ab4c9e086?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27%25E8%2590%259D%25E8%258E%2589%25EF%25BC%258C%25E6%25B8%2585%25E7%25BA%25AF%25E8%2590%259D%25E8%258E%2589%25E9%25A9%25AC%25E5%25B0%25BE.7z.003&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241207T091633Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=Y60FITYLOX7N6UJWBOEE%2F20241207%2Fdefault%2Fs3%2Faws4_request&X-Amz-Signature=ce0022ade659db0b8a305b8ac016c307d071923d46f22737634f369814f54ee3"
          
#      - name: Push
#        run: |
#          git config --local user.name "github-actions"
#          git config --local user.email "github-actions@github.com"
#          git add Download/good/1
#          git commit -m "Update 1"
#          git push origin main

      - name: Unziper
        run: |
          cd Download/
          chmod +x unzipper.sh
          export EXTRA=true
          export password=ruoyuchen
          export crypt=false
          ls -ltrah
          ./unzipper.sh
          tree
          ls -ltrah

      - name: Check
        shell: bash
        run: |
          cd Download/
          ls -ltrah
          ls -ltra
          tree
          
#      - name: Upload
#        uses: actions/upload-artifact@v4
#        with:
#          name: mp4
#          path: Download/*mp*
#          compression-level: 0


      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.0.7  # 使用创建的标签
          name: mp4
          #tag_name: ${{ github.ref }}
          #name: ${{ github.ref }}
          #body: TODO New Release.
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            Download/*mp*



#            Download/HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Medium.ttf
  
            
#      - name: Upload to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: |
#            Download/084.mp4
#            Download/zip.zip
#          tag: ${{ github.ref }}
#          overwrite: true
#          file_glob: true
  
#      - name: Help
#        shell: bash
#        run: |
#          cd Download/字体合并补全工具-简体中文-1.1.0-linux-amd64
#          ./merge-otd --help
#          ./otfccbuild  --help
#          ./otfccdump  --help
                    

