name: Download File

on:
  push:
  workflow_dispatch:
    inputs:
      task:
        description: "Download File And Unzip"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Create a new tag
        id: create_tag
        run: |
           TAG_NAME="v0.2.1"  # 这里设置你想要的标签名
           git tag $TAG_NAME
           git push origin $TAG_NAME

      - name: Install Depends
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip p7zip-full tar gzip bzip2 xz-utils tree unrar lz4 zstd

      - name: Download
        run: |
          cd Download/
          chmod +x unzipper.sh env.sh downloader.sh
          # source env.sh
          wget -O 1.7z.001 "https://ykj-eos-wx2-01.eos-wuxi-3.cmecloud.cn/5b23eb59a6194d3885db6cbd9ac5440a086?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27%25E9%2585%2592.7z.001&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250116T050043Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=Y60FITYLOX7N6UJWBOEE%2F20250116%2Fdefault%2Fs3%2Faws4_request&t=2&u=1039816495805071512&ot=personal&oi=1039816495805071512&f=Fgc4WWHEqzyB6cqc09SRAapRspBoLKtgg&X-Amz-Signature=2329d08dbd348ead781c84a081d6dbae1b90280e1ff406e9e852f7fd53c266e5"
          wget -O 1.7z.002 "https://ykj-eos-wx2-01.eos-wuxi-3.cmecloud.cn/34055ab21a514079aac58f4a7c702d82086?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27%25E9%2585%2592.7z.002&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250116T050056Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=Y60FITYLOX7N6UJWBOEE%2F20250116%2Fdefault%2Fs3%2Faws4_request&t=2&u=1039816495805071512&ot=personal&oi=1039816495805071512&f=FmWkVjbUFlU-qMkui3DNEz4zLp8_PBYJP&X-Amz-Signature=78a4345e17d6dbed6d73b7ceb5df49851d7116fb9e96e3d6710cdabb07359b22"
          wget -O 1.7z.003 "https://ykj-eos-wx2-01.eos-wuxi-3.cmecloud.cn/186d726c29794f3ba98078625c850d4c086?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27%25E9%2585%2592.7z.003&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250116T050108Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=Y60FITYLOX7N6UJWBOEE%2F20250116%2Fdefault%2Fs3%2Faws4_request&t=2&u=1039816495805071512&ot=personal&oi=1039816495805071512&f=Fi__uTXqakFILRjLQFLpHA55dXA8AmodS&X-Amz-Signature=8bb808f5347a556e6577767ec88244f1f91c74841d54d46660f25980e47b6aca"
          # wget -O 1.7z.004 "https://github.com/5hes/MyToolBox/releases/download/v0.2.0/1.7z.004"
          
#      - name: Push
#        run: |
#          git config --local user.name "github-actions"
#          git config --local user.email "github-actions@github.com"
#          git add Download/good/1
#          git commit -m "Update 1"
#          git push origin main

      - name: Unziper
        run: |
          cd Download/
          chmod +x unzipper.sh
          export EXTRA=true
          export password=awfx
          # sen1
          # jntm
          export crypt=false
          ls -ltrah
          # ./unzipper.sh
          mkdir crypt
          # echo "#!/bin/bash" > unzip
          # echo "7z x -pawfx 1.7z.001 -o crypt" > unzip
          # echo "7z x 1.7z.001" > unzip
          # chmod +x unzip
          # ./unzip
          7z x 1.7z.001 -ooutput
          tar -zcvf out.tar output
          tree
          cd output
          ls -ltrah

      - name: Check
        shell: bash
        run: |
          cd Download/output
          ls -ltrah
          ls -ltra
          tree
          
#      - name: Upload
#        uses: actions/upload-artifact@v4
#        with:
#          name: mp4
#          path: Download/*mp*
#          compression-level: 0


      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.2.1
          name: mp4 jiud
          #tag_name: ${{ github.ref }}
          #name: ${{ github.ref }}
          #body: TODO New Release.
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            Download/out.tar
            Download/output/*mp4
            Download/*7z*
            

#            Download/out.tar
#            Download/*7z*
#            Download/HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Medium.ttf
  
            
#      - name: Upload to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: |
#            Download/084.mp4
#            Download/zip.zip
#          tag: ${{ github.ref }}
#          overwrite: true
#          file_glob: true
  
#      - name: Help
#        shell: bash
#        run: |
#          cd Download/字体合并补全工具-简体中文-1.1.0-linux-amd64
#          ./merge-otd --help
#          ./otfccbuild  --help
#          ./otfccdump  --help
                    

