name: Download File

on:
  push:
  workflow_dispatch:
    inputs:
      task:
        description: "Download File And Unzip"
        required: true
        type: boolean

permissions: write-all

jobs:
  task:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Create a new tag
        id: create_tag
        run: |
           TAG_NAME="v0.2.3"  # 这里设置你想要的标签名
           git tag $TAG_NAME
           git push origin $TAG_NAME

      - name: Install Depends
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip p7zip-full tar gzip bzip2 xz-utils tree unrar lz4 zstd

      - name: Download
        run: |
          cd Download/
          chmod +x unzipper.sh env.sh downloader.sh
          # source env.sh
          wget -O 1.7z.001 "https://hcy-wx-14.eos-wuxi-3.cmecloud.cn/MBe1bf2b59108586c844d6efd01c98a3a2?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%279.001%25E5%2588%25A0&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250116T053626Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=Y60FITYLOX7N6UJWBOEE%2F20250116%2Fdefault%2Fs3%2Faws4_request&t=2&u=1039816495805071512&ot=personal&oi=1039816495805071512&f=Fqj8ld7-I_RC4sS7KWJJJGr-dlzXFiOoQ&X-Amz-Signature=121797760553399c082b249ce01376b6d298cbe92d4153fd6585fe8e99f4e4b8"
          wget -O 1.7z.002 "https://hcy-wx-14.eos-wuxi-3.cmecloud.cn/MBd705308ca678282709504be82d56d51e?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%279.002&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250116T053647Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=Y60FITYLOX7N6UJWBOEE%2F20250116%2Fdefault%2Fs3%2Faws4_request&t=2&u=1039816495805071512&ot=personal&oi=1039816495805071512&f=Fi9vIxz3IcgfxMn79RqhMEZ55eoVHyGUH&X-Amz-Signature=2b4b4601526aca70975e046a6910369da0e319a076d4cb0d6d20eb516371e1b2"
          # wget -O 1.7z.003 ""
          # wget -O 1.7z.004 "https://github.com/5hes/MyToolBox/releases/download/v0.2.0/1.7z.004"
          
#      - name: Push
#        run: |
#          git config --local user.name "github-actions"
#          git config --local user.email "github-actions@github.com"
#          git add Download/good/1
#          git commit -m "Update 1"
#          git push origin main

      - name: Unziper
        run: |
          cd Download/
          chmod +x unzipper.sh
          export EXTRA=true
          export password=awfx
          # sen1
          # jntm
          export crypt=false
          ls -ltrah
          # ./unzipper.sh
          mkdir crypt
          # echo "#!/bin/bash" > unzip
          # echo "7z x -pawfx 1.7z.001 -o crypt" > unzip
          # echo "7z x 1.7z.001" > unzip
          # chmod +x unzip
          # ./unzip
          mkdir out
          cd out
          export sb=$PWD
          cd ..

          7z x -pruoyuchen 1.7z.001 -ooutput
          # cd output
          # 7z x -pruoyuchen *001
          # find . -name "*mp4" -exec mv {} $sb \;
          # rm -rf *
          # mv $sb/* .
          
          # cd ..
          tar -zcvf out.tar output
          tree
          cd output
          ls -ltrah

      - name: Check
        shell: bash
        run: |
          cd Download/output
          ls -ltrah
          ls -ltra
          tree
          
#      - name: Upload
#        uses: actions/upload-artifact@v4
#        with:
#          name: mp4
#          path: Download/*mp*
#          compression-level: 0


      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.2.3
          name: mp4 jiudian mm
          #tag_name: ${{ github.ref }}
          #name: ${{ github.ref }}
          #body: TODO New Release.
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            Download/out.tar
            Download/output/*mp4


#            Download/*7z*            
#            Download/out.tar
#            Download/*7z*
#            Download/HarmonyOS Sans /HarmonyOS_Sans_SC/HarmonyOS_SansSC_Medium.ttf
  
            
#      - name: Upload to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: |
#            Download/084.mp4
#            Download/zip.zip
#          tag: ${{ github.ref }}
#          overwrite: true
#          file_glob: true
  
#      - name: Help
#        shell: bash
#        run: |
#          cd Download/字体合并补全工具-简体中文-1.1.0-linux-amd64
#          ./merge-otd --help
#          ./otfccbuild  --help
#          ./otfccdump  --help
                    

