name: Download File

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Download File And Unzip"
        required: true
        type: boolean
        
jobs:
  Download:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Install Depends
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip p7zip-full tar gzip bzip2 xz-utils tree unrar lz4 zstd


      - name: Set Env And Download
        shell: bash
        run: |
          cd Download
          chmod +x unzipper.sh env.sh
          source env.sh
          export EXTRA=true
          export password=sy66
          export crypt=true
          wget -O -q 084.7z.001 "https://ykj-eos-dg5-01.eos-dongguan-6.cmecloud.cn/67d76432232444c091cd37037920b982086?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27084.7z.001&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241202T100345Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=9T1UKBIX6OJSR5XN2F2T%2F20241202%2Fdefault%2Fs3%2Faws4_request&X-Amz-Signature=9b0609d50ab832a4c103edc7fa017c88ba580a1010d3b751cc0e50a59e368e31"
          wget -O -q 084.7z.002 "https://ykj-eos-dg5-01.eos-dongguan-6.cmecloud.cn/85f1effe4cbd40f58bccabb3b0220002086?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27084.7z.002&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241202T100310Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=9T1UKBIX6OJSR5XN2F2T%2F20241202%2Fdefault%2Fs3%2Faws4_request&X-Amz-Signature=db56a1386815c7b11cd39d737d357fdab3cc39c12df6475f14a376cd989e3d61"
          ls -ltrah
          ./unzipper.sh
          tree
          ls -ltrah

      - name: Check
        shell: bash
        run: |
          cd Download
          ls -ltrah
          ls -ltra
          tree

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET }}
          path: Download/${{ env.TARGET }}
          compression-level: 0

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/my*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
  
#      - name: Help
#        shell: bash
#        run: |
#          cd Download/字体合并补全工具-简体中文-1.1.0-linux-amd64
#          ./merge-otd --help
#          ./otfccbuild  --help
#          ./otfccdump  --help
                    

