name: Download File

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Download File And Unzip"
        required: true
        type: boolean

permissions:
  contents: write  # 允许写入内容
  issues: write    # 允许写入问题
  pull-requests: write  # 允许写入拉取请求
        
jobs:
  Download:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Install Depends
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip p7zip-full tar gzip bzip2 xz-utils tree unrar lz4 zstd


      - name: Set Env And Download
        shell: bash
        run: |
          cd Download
          chmod +x unzipper.sh env.sh
          source env.sh
          export EXTRA=true
          export password=sy66
          export crypt=true
          wget -q -O 084.7z.001 "https://ykj-eos-dg5-01.eos-dongguan-6.cmecloud.cn/67d76432232444c091cd37037920b982086?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27084.7z.001&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241205T045628Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=9T1UKBIX6OJSR5XN2F2T%2F20241205%2Fdefault%2Fs3%2Faws4_request&X-Amz-Signature=8569323dd9c1d3866150253f5b379439b59d644dc794adce4c9e61f3075c244c"
          wget -q -O 084.7z.002 "https://ykj-eos-dg5-01.eos-dongguan-6.cmecloud.cn/85f1effe4cbd40f58bccabb3b0220002086?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27084.7z.002&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241205T045558Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Credential=9T1UKBIX6OJSR5XN2F2T%2F20241205%2Fdefault%2Fs3%2Faws4_request&X-Amz-Signature=7043dd2af47305544172d43e9454157de77d495fead3edf355183eee0dff68c5"
          ls -ltrah
          ./unzipper.sh
          tree
          ls -ltrah
          mv 084.mp4（删） 084.mp4
          lz4 084.mp4 zip.zip

      - name: Check
        shell: bash
        run: |
          cd Download
          ls -ltrah
          ls -ltra
          tree
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mp4
          path: Download/084.mp4
          compression-level: 0

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: zip
          path: Download/zip.zip
          compression-level: 0

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          #body: TODO New Release.
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
            Download/zip.zip
            Download/084.mp4
            
#      - name: Upload to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: |
#            Download/084.mp4
#            Download/zip.zip
#          tag: ${{ github.ref }}
#          overwrite: true
#          file_glob: true
  
#      - name: Help
#        shell: bash
#        run: |
#          cd Download/字体合并补全工具-简体中文-1.1.0-linux-amd64
#          ./merge-otd --help
#          ./otfccbuild  --help
#          ./otfccdump  --help
                    

