name: Convert and Merge Fonts

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Merge Font"
        required: true
        type: boolean

jobs:
  convert_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: |
          sudo apt-get install ttfautohint
          pip install fonttools

      - name: Convert OTF to TTF and remove hinting
        run: |
          wget $(cat link_sc) && rm link_sc
          wget -O eng.ttf $(cat link_en) && rm link_en
          cd FontTools/MergeFont
          for font in *.otf; do
            ttx -o "${font%.otf}.ttf" "$font"
            ttfautohint -d "${font%.otf}.ttf" "${font%.otf}-nohint.ttf"
          done

      - name: Merge fonts
        run: |
          fonttools merge -o merged-font.ttf *-nohint.ttf eng.ttf

      - name: Upload merged font
        uses: actions/upload-artifact@v4
        with:
          name: merged-font
          path: FontTools/MergeFont/merged-font.ttf
