name: Merge Font Cpp

on:
  push:
  workflow_dispatch:
    inputs:
      Merge:
        description: Merge Font Use Cpp
        required: true
        type: boolean

permissions: write-all
jobs:
  Merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Replace software sources with the latest
      run: |
        # 删除原有的软件源
        sudo rm -f /etc/apt/sources.list

        # 添加最新的 Ubuntu 24.04 (Noble Numbat) 官方软件源
        echo "deb http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse" | sudo tee /etc/apt/sources.list
        echo "deb http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
        echo "deb http://archive.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
        echo "deb http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list

        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-19 main" | sudo tee /etc/apt/sources.list.d/llvm-toolchain.list

    - name: Add Ubuntu GPG key
      run: |
        # 添加 Ubuntu 官方 GPG 密钥
        curl -fsSL http://archive.ubuntu.com/ubuntu/project/ubuntu-archive-keyring.gpg | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/ubuntu.gpg

    - name: Create a new tag
      run: |
        # TAG_NAME="v0.1.0-font"
        # git tag $TAG_NAME
        # git push origin $TAG_NAME

    - name: Install dependencies
      shell: bash
      run: |
        cd FontTools/MergeFont
        sudo apt-get update
        sudo apt-get install python3 fontconfig fontforge python3-fontforge -y
        # xz-utils ttfautohint
        # python -m pip install foundrytools-cli
        pip install fonttools
        # pip install otf2ttf

    - name: Install ftcli
      run: |
        # git clone https://github.com/ftCLI/FoundryTools-CLI-2.git
        # cp FoundryTools-CLI-2/foundrytools_cli_2/cli/converter/tasks/ttf_to_otf.py FontTools/MergeFont
        # cd FoundryTools-CLI-2
        # pip install .
        
    - name: Check PATH
      run: |
        # ft-cli
        # pip show foundrytools-cli-2
        # ft-cli --help
        
    - name: Download Tools
      shell: bash
      run: |
        cd FontTools/MergeFont
        wget -O zip.zip "https://github.com/nowar-fonts/Warcraft-Font-Merger/releases/download/v1.1.0/WarFontMerger-SC-1.1.0-linux-amd64.tar.xz"
        tar -xf zip.zip
        
    - name: Download Fonts
      shell: bash
      run: |
        cd FontTools/MergeFont
        wget -O Chinese.otf "https://github.com/ACT-02/PingFang-for-Windows/raw/refs/heads/main/PingFangSC-Semibold.otf"
        # wget -O Chinese.otf $(cat link_sc)
        wget -O English.otf "https://github.com/JetBrains/JetBrainsMono/raw/refs/heads/master/fonts/otf/JetBrainsMono-SemiBold.otf"
        # wget -O English.ttf $(cat link_en)
        
    - name: Download fonts-2
      run: |
        mkdir work-2 && cd work-2
        wget "https://github.com/5hes/Warcraft-Font-Merger/releases/download/v1.2.0/merge-otd"
        wget "https://github.com/5hes/Warcraft-Font-Merger/releases/download/v1.2.0/otfccbuild"
        wget "https://github.com/5hes/Warcraft-Font-Merger/releases/download/v1.2.0/otfccdump"
        cp ../FontTools/MergeFont/English.otf .
        cp ../FontTools/MergeFont/Chinese.otf .
        chmod +x otfccbuild otfccdump merge-otd
        ls -l
        ls -l ../FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64/otfccdump
        ls -l ../FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64/otfccbuild
        # ../FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64/otfccdump --help
        # ../FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64/otfccbuild --help
        # ./otfccdump --help
        # ./otfccbuild --help
        
    - name: otf2ttf
      shell: bash
      run: |
        cd FontTools/MergeFont/
        mv 字体合并补全工具-简体中文-1.1.0-linux-amd64 ..
        cp * ../字体合并补全工具-简体中文-1.1.0-linux-amd64
        mv ../字体合并补全工具-简体中文-1.1.0-linux-amd64 .
        cd 字体合并补全工具-简体中文-1.1.0-linux-amd64
        ls -ltrah && ls -ltra
        # ft-cli converter ttf2otf --mode tx English.ttf
          
    - name: Merge Font
      shell: bash
      run: |
        cd FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64
        ls -ltrah && ls -ltra
        ./otfccdump --ignore-hints --name-by-hash --hex-cmap --ignore-glyph-order -o Eng.otd "English.otf"
        ./otfccdump --ignore-hints --name-by-hash --hex-cmap --ignore-glyph-order -o Cjk.otd "Chinese.otf"
        ./merge-otd Eng.otd Cjk.otd
        ./otfccbuild -q --keep-average-char-width -O3 -o merged.otf Eng.otd
        ./otfccbuild -q --keep-average-char-width --merge-lookups --subroutinize --short-post --merge-features --ignore-glyph-order --force-cid -O3 -o merged-opt.otf Eng.otd
        ls -ltrah && ls -ltra
        # fontforge -script optimize_glyph.py merged.otf
        # ls -ltrah && ls -ltra
        
    - name: Merge font-2
      run: |
        cd work-2
        ls -ltrah && ls -ltra
        ./otfccdump --ignore-hints --name-by-hash --hex-cmap --ignore-glyph-order -o Eng.otd "English.otf"
        ./otfccdump --ignore-hints --name-by-hash --hex-cmap --ignore-glyph-order -o Cjk.otd "Chinese.otf"
        ./merge-otd Eng.otd Cjk.otd
        ./otfccbuild -q --keep-average-char-width -O3 -o merged-2.otf Eng.otd
        ./otfccbuild -q --keep-average-char-width --merge-lookups --subroutinize --short-post --merge-features --ignore-glyph-order --force-cid -O3 -o merged-2-opt.otf Eng.otd
        ls -ltrah && ls -ltra
        exit 66
        
    - name: Fix
      shell: bash
      run: |
        cd FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64
        cp ../fix-cpp.py .
        cp merged.otf merged-origin.otf
        # python fix-cpp.py
        # python fix-spacing.py merged.otf 100 merged-100.otf

#     - name: Upload artifact fixed
#       uses: actions/upload-artifact@v4
#       with:
#         name: merged
#         path: ./FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64/merged.otf

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v0.1.0-font
        name: PingFang@ACT-02(github.com) + JetBrainsMono (SemiBold)
        draft: false
        prerelease: false
        files: |
          ./FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64/merged.otf
          ./FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64/English.otf
          ./work-2/merged-2.otf
          
    - name: Get Help
      shell: bash
      run: |
        cd FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64
        ./otfccdump --help
        ./otfccbuild --help

    - name: Check info
      run: |
        cd FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64
        file merged.otf
        # echo -e "\n\n\n"
        # echo -e "merged.otf"
        # python getinfo.py merged.otf
        # echo -e "\n\n"
        fc-query -b merged.otf
          
        echo -e "\n\n\n\n\nmerged-fixed.ttf"
        # python getinfo.py merged-fixed.ttf
        echo -e "\n\n"
        # fc-query -b merged-fixed.ttf
          
        echo -e "\n\n\n\n\nmerged-100.ttf"          
        # python getinfo.py merged-100.ttf
        echo -e "\n\n"
        # fc-query -b merged-100.ttf
          
        echo -e "\n\n\n\n\n"          
        ls -ltrah
        ls -ltra
        md5sum *.otf
        


        
