name: Merge Font Cpp

on:
  workflow_dispatch:
    inputs:
      Merge:
        description: Merge Font Use Cpp
        required: true
        type: boolean

permissions: write-all
jobs:
  Merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create a new tag
        run: |
          #TAG_NAME="v0.0.0-font"
          #git tag $TAG_NAME
          #git push origin $TAG_NAME


      - name: Install dependencies
        shell: bash
        run: |
          cd FontTools/MergeFont
          sudo apt-get update
          sudo apt-get install xz-utils python3 ttfautohint
          pip install fonttools
          pip install otf2ttf

      - name: Download Tools
        shell: bash
        run: |
          cd FontTools/MergeFont
          wget -O zip.zip "https://github.com/nowar-fonts/Warcraft-Font-Merger/releases/download/v1.1.0/WarFontMerger-SC-1.1.0-linux-amd64.tar.xz"
          tar -xf zip.zip
        
      - name: Download Fonts
        shell: bash
        run: |
          cd FontTools/MergeFont
          wget -O Chinese.ttf $(cat link_sc)
          wget -O English.ttf $(cat link_en)

      - name: otf2ttf
        shell: bash
        run: |
          cd FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64
          mv ../Chinese.ttf .
          mv ../English.ttf .
          ls -ltrah && ls -ltra
          # otf2ttf Chinese.otf
          
      - name: Build Merge Font
        shell: bash
        run: |
          cd FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64
          ls -ltrah && ls -ltra
          ./otfccdump --ignore-hints -o Eng.otd "English.ttf"
          ./otfccdump --ignore-hints -o Cjk.otd "Chinese.ttf"
          ./merge-otd Eng.otd Cjk.otd
          ./otfccbuild -q -O3 -o merged.ttf Eng.otd
          ls -ltrah && ls -ltra

      - name: Fix
        shell: bash
        run: |
          cd FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64
          cp ../fix-cpp.py .
          python fix-cpp.py
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: merged
          path: ./FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64/merged.ttf

      - name: Upload artifact fixed
        uses: actions/upload-artifact@v4
        with:
          name: merged-fixed
          path: ./FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64/merged-fixed.ttf

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.0.0-font
          name: Pingfang-sc + IosevkaCostom
          draft: false
          prerelease: false
          files: |
            ./FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64/merged-fixed.ttf
            ./FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64/merged.ttf

      - name: Get Help
        shell: bash
        run: |
          cd FontTools/MergeFont/字体合并补全工具-简体中文-1.1.0-linux-amd64
          ./otfccdump --help
          ./otfccbuild --help
