name: Push File

on:
  push:
  workflow_dispatch:
    inputs:
      PushFile:
        description: "Download and Push file"
        required: true
        type: boolean
  
jobs:
  push-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pushed file
        run: |
          ls -ltrah
          pwd
          tree
          cd Download/good/1
          wget -q -O 1.7z.001 "https://dl-pc-zb-cf.pds.quark.cn/vmf1VyR9/3295366390/66fd585d1f82f7912d8c4f68a7cb50254c20cdd3/66fd585d7faad73002e1413cbb15f60f60df70d0?Expires=1733514650&OSSAccessKeyId=LTAI5tJJpWQEfrcKHnd1LqsZ&Signature=6GZPh%2FMqzhR0AsI4W31RJn0Ohgc%3D&x-oss-traffic-limit=503316480&response-content-disposition=attachment%3B%20filename%3D%25E6%2589%25BE930%2520%25287%2529.7z.001%3Bfilename%2A%3Dutf-8%27%27%25E6%2589%25BE930%2520%25287%2529.7z.001&callback-var=eyJ4OmF1IjoiLSIsIng6dWQiOiIxNi0wLTUtMi02LU4tNC1OLTEtMTYtMC1OIiwieDpzcCI6IjEwMCIsIng6dG9rZW4iOiI0LWZkYTA2ZjY3NGRkZWExNzdkN2JiZWYxNTBhOTJmNGNlLTgtMS01MDAtNjAxY2E2ZmEzNDMwNDUyZWJhNzAwYzU5OTdmZjlhODMtMC0wLTAtMC00M2MwZTUyZWE4NjU4ZTU2OTVhZmY3ZDBkNTQxZjhmYiIsIng6dHRsIjoiMjE2MDAifQ%3D%3D&callback=eyJjYWxsYmFja0JvZHlUeXBlIjoiYXBwbGljYXRpb24vanNvbiIsImNhbGxiYWNrU3RhZ2UiOiJiZWZvcmUtZXhlY3V0ZSIsImNhbGxiYWNrRmFpbHVyZUFjdGlvbiI6Imlnbm9yZSIsImNhbGxiYWNrVXJsIjoiaHR0cHM6Ly9hdXRoLWNkbi51Yy5jbi9vdXRlci9vc3MvY2hlY2twbGF5IiwiY2FsbGJhY2tCb2R5Ijoie1wiaG9zdFwiOiR7aHR0cEhlYWRlci5ob3N0fSxcInNpemVcIjoke3NpemV9LFwicmFuZ2VcIjoke2h0dHBIZWFkZXIucmFuZ2V9LFwicmVmZXJlclwiOiR7aHR0cEhlYWRlci5yZWZlcmVyfSxcImNvb2tpZVwiOiR7aHR0cEhlYWRlci5jb29raWV9LFwibWV0aG9kXCI6JHtodHRwSGVhZGVyLm1ldGhvZH0sXCJpcFwiOiR7Y2xpZW50SXB9LFwicG9ydFwiOiR7Y2xpZW50UG9ydH0sXCJvYmplY3RcIjoke29iamVjdH0sXCJzcFwiOiR7eDpzcH0sXCJ1ZFwiOiR7eDp1ZH0sXCJ0b2tlblwiOiR7eDp0b2tlbn0sXCJhdVwiOiR7eDphdX0sXCJ0dGxcIjoke3g6dHRsfSxcImR0X3NwXCI6JHt4OmR0X3NwfSxcImhzcFwiOiR7eDpoc3B9LFwiY2xpZW50X3Rva2VuXCI6JHtxdWVyeVN0cmluZy5jbGllbnRfdG9rZW59fSJ9&ud=16-0-5-2-6-N-4-N-1-16-0-N"
          
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add Download/good/1.7z.001  # 添加要推送的文件
          git commit -m "Add 1.7z.001" || echo "No changes to commit"
          git push origin main  # 将更改推送到主分支
